CREATE TABLE IF NOT EXISTS `crm`.`hoa_properties` (
    `id`                    VARCHAR(36)    NOT NULL,
    `parcel_id`             VARCHAR(100)   NOT NULL,
    `arcgis_source`         VARCHAR(50)    NOT NULL,
    `property_name`         VARCHAR(255)   NOT NULL,
    `state`                 CHAR(2)        NOT NULL,
    `address`               VARCHAR(255)   NOT NULL DEFAULT '',
    `city`                  VARCHAR(100)   NOT NULL DEFAULT '',
    `zip`                   VARCHAR(20)    NOT NULL DEFAULT '',
    `estimated_acreage`     DECIMAL(10,4)  DEFAULT NULL,
    `management_company_id` VARCHAR(36)    DEFAULT NULL,
    `association_name`      VARCHAR(255)   DEFAULT NULL,
    `county`                VARCHAR(100)   DEFAULT NULL,
    `units`                 SMALLINT       DEFAULT NULL,
    `status`                VARCHAR(50)    NOT NULL DEFAULT 'uncontacted',
    `branch_id`             VARCHAR(100)   DEFAULT NULL,
    -- prospecting workflow columns (Handoff 15 §3.3 drift reconciliation:
    -- these were live via an out-of-tree migration; now checked in)
    `assigned_to`           VARCHAR(255)   DEFAULT NULL,
    `contact_status`        VARCHAR(50)    DEFAULT NULL,
    `last_contacted`        DATE           DEFAULT NULL,
    `raw_data`              JSON           DEFAULT NULL,
    `arcgis_last_seen_at`   DATETIME       DEFAULT NULL,
    `created_at`            DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`            DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_parcel_source`  (`parcel_id`, `arcgis_source`),
    INDEX `idx_hoa_state`          (`state`),
    INDEX `idx_hoa_status`         (`status`),
    INDEX `idx_hoa_branch_id`      (`branch_id`),
    INDEX `idx_hoa_mgmt_co_id`     (`management_company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
