CREATE TABLE IF NOT EXISTS juniper.leads (
    id                       VARCHAR(36)    NOT NULL,
    source                   VARCHAR(50)    NOT NULL,
    source_ref               VARCHAR(255)   DEFAULT NULL,
    lead_type                VARCHAR(20)    NOT NULL,
    property_name            TEXT           NOT NULL,
    address                  VARCHAR(255)   DEFAULT NULL,
    city                     VARCHAR(100)   DEFAULT NULL,
    state                    VARCHAR(2)     NOT NULL,
    zip                      VARCHAR(20)    DEFAULT NULL,
    lat                      DECIMAL(9,6)   DEFAULT NULL,
    lng                      DECIMAL(9,6)   DEFAULT NULL,
    estimated_acreage        DECIMAL(8,2)   DEFAULT NULL,
    units                    INT            DEFAULT NULL,
    bid_deadline             DATE           DEFAULT NULL,
    estimated_contract_value DECIMAL(15,2)  DEFAULT NULL,
    source_url               TEXT           DEFAULT NULL,
    contact_name             VARCHAR(255)   DEFAULT NULL,
    contact_email            VARCHAR(255)   DEFAULT NULL,
    status                   VARCHAR(30)    NOT NULL DEFAULT 'new',
    assigned_to              VARCHAR(255)   DEFAULT NULL,
    priority                 TINYINT        DEFAULT 0,
    notes                    TEXT           DEFAULT NULL,
    branch_id                VARCHAR(100)   DEFAULT NULL,
    distance_miles           DECIMAL(7,2)   DEFAULT NULL,
    score                    TINYINT UNSIGNED DEFAULT NULL,
    score_factors            JSON           DEFAULT NULL,
    raw_data                 JSON           DEFAULT NULL,
    -- canonical properties.id (Handoff 15; logical ref, no FK). Nullable —
    -- manual leads may have none. Replaces the removed hoa_property_id.
    property_id              VARCHAR(36)    DEFAULT NULL,
    created_at               DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_source_ref` (`source`, `source_ref`),
    INDEX `idx_status`       (`status`),
    INDEX `idx_state`        (`state`),
    INDEX `idx_lead_type`    (`lead_type`),
    INDEX `idx_bid_deadline` (`bid_deadline`),
    INDEX `idx_branch_id`    (`branch_id`),
    INDEX `idx_score`        (`score`),
    INDEX `idx_property_id`  (`property_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
