CREATE TABLE IF NOT EXISTS `juniper`.`higher_gov_opportunities` (
    `opp_key`             VARCHAR(255)  NOT NULL,
    `version_key`         VARCHAR(255)  DEFAULT NULL,
    `source_id`           VARCHAR(255)  DEFAULT NULL,
    `title`               TEXT          DEFAULT NULL,
    `opp_cat`             VARCHAR(100)  DEFAULT NULL,
    `opp_type`            VARCHAR(100)  DEFAULT NULL,
    `naics_code`          VARCHAR(20)   DEFAULT NULL,
    `psc_code`            VARCHAR(20)   DEFAULT NULL,
    `set_aside`           VARCHAR(255)  DEFAULT NULL,
    `sole_source`         TINYINT(1)    DEFAULT NULL,
    `agency_name`         VARCHAR(255)  DEFAULT NULL,
    `agency_key`          INT           DEFAULT NULL,
    `agency_type`         VARCHAR(100)  DEFAULT NULL,
    `agency_abbreviation` VARCHAR(50)   DEFAULT NULL,
    `posted_date`         DATE          DEFAULT NULL,
    `captured_date`       DATE          DEFAULT NULL,
    `due_date`            DATE          DEFAULT NULL,
    `pop_city`            VARCHAR(100)  DEFAULT NULL,
    `pop_state`           VARCHAR(10)   DEFAULT NULL,
    `pop_zip`             VARCHAR(20)   DEFAULT NULL,
    `pop_country`         VARCHAR(10)   DEFAULT NULL,
    `val_est_low`         DECIMAL(15,2) DEFAULT NULL,
    `val_est_high`        DECIMAL(15,2) DEFAULT NULL,
    `contact_title`       VARCHAR(255)  DEFAULT NULL,
    `contact_name`        VARCHAR(255)  DEFAULT NULL,
    `contact_email`       VARCHAR(255)  DEFAULT NULL,
    `contact_phone`       VARCHAR(50)   DEFAULT NULL,
    `source_url`          TEXT          DEFAULT NULL,
    `highergov_url`       TEXT          DEFAULT NULL,
    `document_path`       VARCHAR(255)  DEFAULT NULL,
    `documents`           JSON          DEFAULT NULL,
    `scraped_at`          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `search_keyword`      VARCHAR(255)  DEFAULT NULL,
    PRIMARY KEY (`opp_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
