CREATE TABLE IF NOT EXISTS `juniper`.`sam_gov_opportunities` (
    `notice_id`              VARCHAR(255)  NOT NULL,
    `solicitation_number`    VARCHAR(255)  DEFAULT NULL,
    `type`                   VARCHAR(100)  DEFAULT NULL,
    `base_type`              VARCHAR(100)  DEFAULT NULL,
    `title`                  TEXT          DEFAULT NULL,
    `organization_name`      VARCHAR(255)  DEFAULT NULL,
    `organization_type`      VARCHAR(100)  DEFAULT NULL,
    `naics_code`             VARCHAR(20)   DEFAULT NULL,
    `classification_code`    VARCHAR(50)   DEFAULT NULL,
    `type_of_set_aside`      VARCHAR(50)   DEFAULT NULL,
    `type_of_set_aside_desc` VARCHAR(255)  DEFAULT NULL,
    `full_parent_path_name`  TEXT          DEFAULT NULL,
    `full_parent_path_code`  TEXT          DEFAULT NULL,
    `active`                 VARCHAR(10)   DEFAULT NULL,
    `posted_date`            DATE          DEFAULT NULL,
    `response_deadline`      DATETIME      DEFAULT NULL,
    `archive_date`           DATE          DEFAULT NULL,
    `archive_type`           VARCHAR(50)   DEFAULT NULL,
    `pop_street`             VARCHAR(255)  DEFAULT NULL,
    `pop_city`               VARCHAR(100)  DEFAULT NULL,
    `pop_state`              VARCHAR(100)  DEFAULT NULL,
    `pop_zip`                VARCHAR(20)   DEFAULT NULL,
    `pop_country`            VARCHAR(100)  DEFAULT NULL,
    `office_city`            VARCHAR(100)  DEFAULT NULL,
    `office_state`           VARCHAR(100)  DEFAULT NULL,
    `office_zip`             VARCHAR(20)   DEFAULT NULL,
    `office_country_code`    VARCHAR(10)   DEFAULT NULL,
    `contact_name`           VARCHAR(255)  DEFAULT NULL,
    `contact_email`          VARCHAR(255)  DEFAULT NULL,
    `contact_phone`          VARCHAR(50)   DEFAULT NULL,
    `contact_type`           VARCHAR(20)   DEFAULT NULL,
    `award_date`             DATE          DEFAULT NULL,
    `award_number`           VARCHAR(255)  DEFAULT NULL,
    `award_amount`           DECIMAL(15,2) DEFAULT NULL,
    `awardee_name`           VARCHAR(255)  DEFAULT NULL,
    `awardee_uei`            VARCHAR(50)   DEFAULT NULL,
    `awardee_location`       VARCHAR(255)  DEFAULT NULL,
    `ui_link`                TEXT          DEFAULT NULL,
    `description_url`        TEXT          DEFAULT NULL,
    `additional_info_link`   TEXT          DEFAULT NULL,
    `resource_links`         JSON          DEFAULT NULL,
    `scraped_at`             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `search_keyword`         VARCHAR(255)  DEFAULT NULL,
    PRIMARY KEY (`notice_id`),
    INDEX `idx_pop_state`         (`pop_state`),
    INDEX `idx_posted_date`       (`posted_date`),
    INDEX `idx_response_deadline` (`response_deadline`),
    INDEX `idx_search_keyword`    (`search_keyword`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
